version: '3.8'
services:
  ingest:
    build: ./ingest
    ports:
      - "1935:1935"   # RTMP input
      - "8080:80"     # Health & metrics
    environment:
      - STREAM_KEY=${STREAM_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

  chat:
    build: ./chat
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6-alpine
    command: ["redis-server","--maxmemory-policy","allkeys-lru"]

  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - ingest
      - chat

networks:
  default:
    external:
      name: clipt-net
